name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm resource destruction'
        required: true
        default: ''

permissions:
  contents: read
  pull-requests: write
  issues: write


jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Validate Confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]; then
          echo "❌ Destruction not confirmed. Please type 'DESTROY' to proceed."
          exit 1
        fi
        echo "✅ Destruction confirmed. Proceeding..."

    - name: Checkout
      uses: actions/checkout@v4

    - name: Terraform fmt check
      uses: dflook/terraform-fmt-check@1a3cda175d4cc03f253d0b5734e756cdefc2d04c # v2.1.0
      with:
        path: 2025-06-29-modular-hack-weekend/infrastructure

    - name: Terraform validate
      uses: dflook/terraform-validate@1a3cda175d4cc03f253d0b5734e756cdefc2d04c # v2.1.0
      with:
        path: 2025-06-29-modular-hack-weekend/infrastructure

    - name: Terraform destroy
      uses: dflook/terraform-destroy@1a3cda175d4cc03f253d0b5734e756cdefc2d04c # v2.1.0
      with:
        path: 2025-06-29-modular-hack-weekend/infrastructure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LAMBDALABS_API_KEY: ${{ secrets.LAMBDALABS_API_KEY }}

    - name: Comment Results
      uses: actions/github-script@v7
      with:
        script: |
          const output = `### 🔥 Infrastructure Destroyed Successfully!
          
          All Lambda Cloud GPU resources have been destroyed.
          
          **Cost Impact**: Billing has stopped for all provisioned resources.
          
          **Next Steps**: 
          - Resources can be re-deployed via PR merge to main branch
          - Check Lambda Cloud console to verify resource cleanup
          `;
          
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: output
          });